In [1]:
import torch

In [11]:
rew = torch.linspace(10,,6,dtype=float)
rew

tensor([10., 10., 10., 10., 10., 10.], dtype=torch.float64)

In [18]:
b = torch.rand((4,6),dtype = float)
b

tensor([[0.0704, 0.3156, 0.1959, 0.2582, 0.9185, 0.6724],
        [0.0408, 0.5974, 0.4589, 0.5392, 0.6404, 0.3297],
        [0.2696, 0.0774, 0.9438, 0.5115, 0.7127, 0.5484],
        [0.5217, 0.6422, 0.3969, 0.0483, 0.1736, 0.5403]], dtype=torch.float64)

In [19]:
b.mul(rew)

tensor([[0.7035, 3.1562, 1.9591, 2.5821, 9.1846, 6.7240],
        [0.4078, 5.9741, 4.5892, 5.3917, 6.4037, 3.2970],
        [2.6960, 0.7740, 9.4385, 5.1152, 7.1271, 5.4841],
        [5.2169, 6.4224, 3.9690, 0.4834, 1.7359, 5.4029]], dtype=torch.float64)

In [20]:
b.type()

'torch.DoubleTensor'

In [26]:
a =torch.rand((4,6),dtype = float)
a

tensor([[0.1980, 0.8861, 0.1390, 0.2125, 0.0932, 0.2173],
        [0.5579, 0.3350, 0.3092, 0.1416, 0.4797, 0.6289],
        [0.4009, 0.3881, 0.2827, 0.5299, 0.9880, 0.6572],
        [0.6824, 0.0794, 0.5055, 0.3060, 0.8900, 0.4643]], dtype=torch.float64)

In [31]:
a= a.type(b.type())
a

tensor([[0.1980, 0.8861, 0.1390, 0.2125, 0.0932, 0.2173],
        [0.5579, 0.3350, 0.3092, 0.1416, 0.4797, 0.6289],
        [0.4009, 0.3881, 0.2827, 0.5299, 0.9880, 0.6572],
        [0.6824, 0.0794, 0.5055, 0.3060, 0.8900, 0.4643]], dtype=torch.float64)